### ISSUE TITLE
[FEATURE REQUEST] implement fake-useragent library

### ISSUE THREAD

**Issue by pyccino** [sushil-rgb/AmazonMe#9]
**Description:**
I would like to suggest implementing the use of the "fake-useragent" library (https://pypi.org/project/fake-useragent/) instead of the current approach, which involves managing a large .txt file of user agents and selecting one randomly.

**Motivation:**
The "fake-useragent" library provides a more streamlined and efficient solution for handling user agents. Instead of reading from a hefty 844KB .txt file, the library generates user agents dynamically, eliminating the need for file I/O operations and enhancing performance.

**Benefits:**
1. **Reduced File I/O Overhead:** The current method involves opening and reading a large .txt file, which can be time-consuming. By using "fake-useragent," we can eliminate the need for file operations altogether, resulting in faster execution times.

2. **Dynamic User Agent Generation:** "fake-useragent" generates user agents on-the-fly, ensuring a diverse set of user agents without the need for maintaining an extensive list in a text file.

3. **Ease of Integration:** Implementing "fake-useragent" is straightforward and can potentially lead to cleaner and more maintainable code.

**References:**
- [fake-useragent on PyPI](https://pypi.org/project/fake-useragent/)
- [fake-useragent GitHub Repository](https://github.com/hellysmile/fake-useragent)

**Comment by sushil-rgb** [comment]
Once again thank you @pyccino . I'll definitely be incorporating this into my project. Your assistance is greatly appreciated.
